"""
fraud_detection_prototype.py

Initial technical prototype for the AI-based fraud detection and
transaction security module described in the petitioner's proposed
endeavor (NIW Petition, Prong I).

This prototype demonstrates, at proof-of-concept scale, the three core
technical approaches described in the endeavor:

  1. Supervised classification  -> flags transactions matching known
     fraud patterns (trained on labeled historical-style data).
  2. Unsupervised anomaly detection -> flags previously unseen
     suspicious behavior without relying on labels.
  3. Network/graph-based analysis -> traces connections between
     accounts to surface layering/structuring patterns relevant to
     anti-money-laundering (AML) review.

Data: 100% synthetic, generated by generate_synthetic_data.py. No real
customer, account, or transaction data from any financial institution
is used or represented.

Author: Fatima Altagracia Genao Mendez
Date: September 2026
"""

import networkx as nx
import numpy as np
import pandas as pd
from sklearn.ensemble import IsolationForest, RandomForestClassifier
from sklearn.metrics import classification_report, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder


def load_data():
    accounts = pd.read_csv("data_accounts.csv")
    transactions = pd.read_csv("data_transactions.csv")
    return accounts, transactions


def engineer_features(transactions: pd.DataFrame, accounts: pd.DataFrame) -> pd.DataFrame:
    """Builds a simple, explainable feature set from the raw transaction log."""
    df = transactions.merge(
        accounts[["account_id", "avg_monthly_activity"]],
        left_on="sender_account", right_on="account_id", how="left",
    )
    df["amount_vs_avg_activity"] = df["amount"] / df["avg_monthly_activity"].replace(0, np.nan)
    df["amount_vs_avg_activity"] = df["amount_vs_avg_activity"].fillna(df["amount_vs_avg_activity"].median())
    df["is_night"] = df["hour_of_day"].between(0, 5).astype(int)

    channel_encoder = LabelEncoder()
    df["channel_encoded"] = channel_encoder.fit_transform(df["channel"])

    feature_cols = [
        "amount", "amount_vs_avg_activity", "hour_of_day", "is_night",
        "channel_encoded", "is_peer_transfer",
    ]
    return df, feature_cols


# ---------------------------------------------------------------------
# 1. Supervised classification component
# ---------------------------------------------------------------------
def run_supervised_classifier(df: pd.DataFrame, feature_cols: list[str]) -> None:
    print("\n" + "=" * 70)
    print("COMPONENT 1: Supervised classification (known fraud patterns)")
    print("=" * 70)

    X = df[feature_cols].astype(float)
    y = df["is_fraud"].astype(int)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, random_state=42, stratify=y
    )

    clf = RandomForestClassifier(n_estimators=200, max_depth=8, class_weight="balanced", random_state=42)
    clf.fit(X_train, y_train)

    y_pred = clf.predict(X_test)
    y_proba = clf.predict_proba(X_test)[:, 1]

    print(classification_report(y_test, y_pred, target_names=["legitimate", "fraud"]))
    print(f"ROC-AUC: {roc_auc_score(y_test, y_proba):.4f}")

    importances = pd.Series(clf.feature_importances_, index=feature_cols).sort_values(ascending=False)
    print("\nTop feature importances:")
    print(importances.to_string())


# ---------------------------------------------------------------------
# 2. Unsupervised anomaly detection component
# ---------------------------------------------------------------------
def run_anomaly_detection(df: pd.DataFrame, feature_cols: list[str]) -> pd.DataFrame:
    print("\n" + "=" * 70)
    print("COMPONENT 2: Unsupervised anomaly detection (unseen patterns)")
    print("=" * 70)

    X = df[feature_cols].astype(float)

    iso = IsolationForest(n_estimators=200, contamination=0.02, random_state=42)
    df = df.copy()
    df["anomaly_score"] = iso.fit_predict(X)  # -1 = anomaly, 1 = normal
    df["is_anomaly"] = (df["anomaly_score"] == -1)

    n_flagged = df["is_anomaly"].sum()
    overlap_with_known_fraud = df.loc[df["is_anomaly"], "is_fraud"].mean()

    print(f"Transactions flagged as anomalous: {n_flagged} ({n_flagged / len(df):.2%} of total)")
    print(f"Share of flagged transactions that match the synthetic fraud ground truth: {overlap_with_known_fraud:.2%}")
    print("(Unsupervised detection is expected to also surface novel patterns not present")
    print(" in the labeled ground truth -- that is its intended purpose.)")

    return df


# ---------------------------------------------------------------------
# 3. Network / graph-based analysis component (AML-style layering)
# ---------------------------------------------------------------------
def run_graph_analysis(transactions: pd.DataFrame) -> None:
    print("\n" + "=" * 70)
    print("COMPONENT 3: Network/graph analysis (account-to-account layering)")
    print("=" * 70)

    peer_txns = transactions[transactions["is_peer_transfer"]]

    G = nx.DiGraph()
    for _, row in peer_txns.iterrows():
        G.add_edge(row["sender_account"], row["receiver_account"], weight=row["amount"])

    print(f"Graph built from peer-to-peer transfers: {G.number_of_nodes()} accounts, {G.number_of_edges()} transfer edges")

    degree_centrality = nx.degree_centrality(G)
    top_accounts = sorted(degree_centrality.items(), key=lambda x: x[1], reverse=True)[:10]

    print("\nTop 10 accounts by connectivity (degree centrality) --")
    print("high connectivity within a tight, mutually-reinforcing cluster is a")
    print("pattern consistent with structuring/layering and warrants AML review:")
    for account, score in top_accounts:
        print(f"  {account}: centrality={score:.4f}, "
              f"in-degree={G.in_degree(account)}, out-degree={G.out_degree(account)}")

    # Community detection (modularity-based) surfaces tightly-interconnected
    # sub-groups even within a single large, mostly-sparse network -- a more
    # realistic proxy for layering rings than raw connected components, which
    # tend to merge into one giant component in networks of this density.
    undirected = G.to_undirected()
    communities = list(nx.algorithms.community.greedy_modularity_communities(undirected, weight="weight"))

    def internal_density(nodes):
        sub = undirected.subgraph(nodes)
        n = sub.number_of_nodes()
        max_edges = n * (n - 1) / 2
        return sub.number_of_edges() / max_edges if max_edges > 0 else 0

    dense_clusters = [c for c in communities if 3 <= len(c) <= 20 and internal_density(c) >= 0.25]
    print(f"\nDetected {len(communities)} account communities via modularity-based clustering;")
    print(f"{len(dense_clusters)} of them are small and densely interconnected (density >= 0.25),")
    print("a pattern consistent with structuring/layering that would be flagged for manual AML")
    print("review in the proposed production design:")
    for c in dense_clusters[:5]:
        print(f"  cluster of {len(c)} accounts, internal density={internal_density(c):.2f}: {sorted(c)}")


if __name__ == "__main__":
    accounts, transactions = load_data()
    df, feature_cols = engineer_features(transactions, accounts)

    run_supervised_classifier(df, feature_cols)
    df_scored = run_anomaly_detection(df, feature_cols)
    run_graph_analysis(transactions)

    print("\n" + "=" * 70)
    print("Prototype run complete. See README.md for architecture notes and")
    print("how each component maps to the production design described in the")
    print("petitioner's Model or Business Plan.")
    print("=" * 70)
